import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { Providers } from './providers';
import { Box, Center, Heading } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Box as='main' maxWidth={'500px'} backgroundColor={'darkblue'} height={'100vh'} rounded={'2xl'} marginInline={'auto'} textColor={'#d5f5ff'} paddingY={4} position={'relative'}>
            <Heading as={'h1'} marginBottom={10}>
              <Center>NoteSpace</Center>
            </Heading>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
